### ISSUE TITLE
is there a guide for monorepo?

### ISSUE THREAD

**Issue by sibelius** [seek-oss/playroom#132]
We have many base components across many packages in our monorepo, what is the best way to setup playroom in this scenario?

For storybook, we have a single storybook that has stories inside all packages

**Comment by michaeltaranto** [comment]
Playroom just needs to be pointed to a single file that exports all the components you want available.
1. Create a file that imports all the required packages
2. Re-export everything from this file
3. In your playroom config point `components` at this new file.

**Comment by sibelius** [comment]
This should be in root, or in a package of monorepo?

**Comment by michaeltaranto** [comment]
I would suggest to co-locate it where ever your playroom setup is, hard to say without seeing the project. Do you have a `FrameComponent` defined anywhere?  If you want to leverage the snippets feature you'll have to create a file for that too, so maybe setting up a playroom folder at the root makes sense?

**Comment by sibelius** [comment]
usually we have some like this: https://github.com/entria/entria-fullstack

in a real app we would have the following packages:

packages
- app
- ui (design system)
- form (form field build blocks)
- charts (generic charts for app)

I'm like my `playroom` to have all components of `ui`, `form` and `charts` packages

**Comment by PeterKow** [comment]
Confirmed, it works ✅  

I moved my `playroom.config` to `root` and just tweak the configuration to UI package `./packages/UI`

```
module.exports = {
    components: './packages/UI/src/native.ts',
    outputPath: './packages/UI/distPlayroom',

    frameComponent: './packages/UI/.playroom/FrameComponent.tsx',
    themes: './packages/UI/src/themes/index.ts',
...
```

also, move scripts to root `pacakge.json`

```
    "playroom": "playroom start",
    "playroom:build": "playroom build"
```

**Comment by maraisr** [comment]
@sibelius this is how our mono-repo works for consumer land code.

- have a package; we called it playroom
- this package imports playroom, and also has a yarn workspace dep on all other things I want to play with. So dep on UI, Charts etc...
- then have a "components.ts" file in that package, that re-exports all the components from those packages. In our case, we just have a `export * from '@autoguru/package-a';`
- then simply `yarn workspace @autoguru/playroom start`.

With snippets; we took inspiration from braid, and have a `.docs.tsx` file sitting next to our components. In consumer land, this file means nothing other than articulate snippets. And in certain cases where a component needs an implementation, we also export a component property from that to use.

The only issue I've found is that if 2 packages have the same name, then the last one wins out. So for this we also have some named exports that prefix the package name. Thinking now, since its webpack driven - I could just require.context and prefix all components.

I will however say; the value of playroom in consumer side isn't all that great. I personally hardly use it.. You tend to be in the screens, talking with real data as the consumer components are being built - and 90% of the time, its just the design system components being used.
