### ISSUE TITLE
Gitlab Addon

### ISSUE THREAD

**Issue by williamjaeholee** [seek-oss/playroom#292]
Thank you team for this great tool! One thing I found about Playroom is that it is a great WYSIWYG Editor that connects well to customized codebases. However, there is currently no ability to save or push code to the connected codebase after a component or edit to the design. Is there any way of integrating Gitlab committing, pull request, and branching features to Playroom?

Thank you!

**Comment by askoufis** [comment]
Thanks for the issue!

Playroom is really more of a prototyping tool, rather than an environment for editing/developing fully-featured components. Playroom is best suited for going from an idea/mockup to a working prototype, but your prototype usually isn't the final finished implementation. For that reason, an integration with Gitlab or similar doesn't really fit with the purpose of the tool.
