### ISSUE TITLE
Support Vue

### ISSUE THREAD

**Issue by stevefan1999-personal** [seek-oss/playroom#61]
[Vue supports JSX as well!](https://vuejs.org/v2/guide/render-function.html#JSX)

**Comment by bmcminn** [comment]
Looking at the source of this app, I'm not sure it would be possible to integrate Vue here =\ Vue 3 is promising some really cool features for developers and integrating into a React based ecosystem like this would hamstring it a lot.

I would assume building a Vue based version of this utility would be a better option, and likely would be easier to coordinate features rather than coming up with some sort of divergent build initializer.

**Comment by bmcminn** [comment]
@markdalgleish is there any consideration for Vue based JSX support in y'alls roadmap? or was this primarily designed as a React utility?

**Comment by stevefan1999-personal** [comment]
but TBH, we could use this as a workaround for now: https://github.com/akxcv/vuera

**Comment by michaeltaranto** [comment]
Given the stack that our teams work with this is not really something we are looking to support. Adding support for something that we do not use will also incur a maintenance cost that we are not looking to take on.

But feel free to fork and adapt to suit your needs though.
